apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- staking-deployment.yaml
- staking-service.yaml
- staking-ingress.yaml
images:
- name: ghcr.io/philiplehmann/staking
  newName: ghcr.io/philiplehmann/staking
  newTag: 22-12-13.6
