apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- staking-deployment.yaml
- staking-service.yaml
- staking-ingress.yaml
images:
- name: harbor.riwi.dev/philiplehmann/staking
  newName: harbor.riwi.dev/philiplehmann/staking
  newTag: 24-11-13.66
