name: build & deploy

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to harbor.riwi.dev registry
        uses: docker/login-action@v3
        with:
          registry: harbor.riwi.dev
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: set version
        run: echo "TAG_VERSION=$(date +'%y-%m-%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          push: true
          cache-from: type=registry,ref=harbor.riwi.dev/philiplehmann/staking:buildcache
          cache-to: type=registry,ref=harbor.riwi.dev/philiplehmann/staking:buildcache,mode=max,image-manifest=true
          tags: |
            harbor.riwi.dev/philiplehmann/staking:latest
            harbor.riwi.dev/philiplehmann/staking:${{ env.TAG_VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: set version
        run: echo "TAG_VERSION=$(date +'%y-%m-%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      - uses: philiplehmann/setup-kustomize@v2.2.5
      - name: deploy
        run: |
          cd kustomize/staking
          kustomize edit set image harbor.riwi.dev/philiplehmann/staking=harbor.riwi.dev/philiplehmann/staking:${{ env.TAG_VERSION }}
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Set image tag to `${{ env.TAG_VERSION }}`
